<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RestaurantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('restaurants')->insert([
            ['district_id'=>1,
            'name'=>'Hemispheres Steak & Seafood Grill',
            'address'=>'Sheraton Hanoi Hotel K5 Nghi Tam, 11 Xuan Dieu Road, Tay Ho, Hà Nội 10000 Việt Nam',
            'phone'=>'02437199000',
            'website'=>'http://www.facebook.com/hemispheres.seafood.steak.grill',
            'open_at'=>'18:00:00', 'close_at'=>'22:30:00',
            'description'=>'Hãy để Hemispheres Steak & Seafood Grill đưa vị giác của quý khách lên chuyến tàu phiêu lưu vòng quanh thế giới với thực đơn độc đáo được thiết kế bởi Bếp trưởng Đức, "đệ tử ruột" của Đầu bếp Xuất sắc nhất Châu Á do The Hotelier bình chọn năm 2017 - Nguyễn Công Chung. Quý khách đã sẵn sàng đắm mình vào tấm bản đồ ẩm thực đa quốc gia và bắt đầu hành trình du ngoạn qua bốn góc bán cầu với những món ăn được kết hợp hoàn hảo từ các loại nguyên liệu nhập khẩu cao cấp và các sản phẩm tươi ngon từ vườn rau hữu cơ do chính tay các đầu bếp của chúng tôi chăm bón? Chúng tối hân hạnh được chào đón!',
            'image'=>'https://media-cdn.tripadvisor.com/media/photo-s/1c/63/74/76/hemispheres-steak-seafood.jpg',
            'star'=>5.0,
            'min_price'=>581395, 'max_price'=>2325581,
            'is_hot'=>1, 'is_active'=>1],

            ['district_id'=>2,
            'name'=>'Puku Cafe and Sports Bar',
            'address'=>'16 Tong Duy Tan, Hà Nội 100000 Việt Nam',
            'phone'=>'0439381745',
            'website'=>'https://www.facebook.com/PukuCafeHanoi/',
            'open_at'=>'7:00:00', 'close_at'=>'21:00:00',
            'description'=>'',
            'image'=>'https://media-cdn.tripadvisor.com/media/photo-s/0c/8f/f6/4c/australian-beef-rib-eye.jpg',
            'star'=>4.5,
            'min_price'=>50000, 'max_price'=>200000,
            'is_hot'=>0, 'is_active'=>1],

            ['district_id'=>1,
            'name'=>'Dalcheeni HANOI',
            'address'=>'100 Xuân Diệu Tứ Liên, Tây Hồ, Hà Nội 100000 Việt Nam',
            'phone'=>'01642405693',
            'website'=>'http://dalcheenivn.com/',
            'open_at'=>'5:30:00', 'close_at'=>'22:30:00',
            'description'=>'',
            'image'=>'https://media-cdn.tripadvisor.com/media/photo-s/11/71/52/fd/west-lake-view.jpg',
            'star'=>5.0,
            'min_price'=>186047, 'max_price'=>465116,
            'is_hot'=>1, 'is_active'=>1],

            ['district_id'=>3,
            'name'=>'HOME Hanoi - HOME Vietnamese Restaurant',
            'address'=>'75 P. Nguyễn Đình Chiểu, Lê Đại Hành, 31 Van Ho 2, Hà Nội 10000 Việt Nam',
            'phone'=>'02439588666',
            'website'=>'http://homevietnameserestaurants.com/',
            'open_at'=>'5:30:00', 'close_at'=>'22:00:00',
            'description'=>'',
            'image'=>'https://media-cdn.tripadvisor.com/media/photo-s/28/11/f0/30/home-hanoi-restaurant.jpg',
            'star'=>5.0,
            'min_price'=>465116, 'max_price'=>697674,
            'is_hot'=>0, 'is_active'=>1],

            ['district_id'=>2,
            'name'=>'Lighthouse Sky Bar & Restaurant',
            'address'=>'27 Hàng Bè Tầng thượng, La Siesta Premium Hàng Bè, Hoàn Kiếm, Hà Nội 100000 Việt Nam',
            'phone'=>'02439290011',
            'website'=>'http://skybars.vn/lighthouse-sky-bar/',
            'open_at'=>'17:00:00', 'close_at'=>'12:00:00',
            'description'=>'',
            'image'=>'https://media-cdn.tripadvisor.com/media/photo-s/26/45/83/47/overview-at-night.jpg',
            'star'=>5.0,
            'min_price'=>186047, 'max_price'=>4883721,
            'is_hot'=>1, 'is_active'=>1],

            ['district_id'=>2,
            'name'=>'Bánh mì Long Hội',
            'address'=>'Số 1 Hàng Dầu Lý Thái Tổ, Hà Nội 10000 Việt Nam',
            'phone'=>'0835116866',
            'website'=>'http://banhmilonghoi.vn/',
            'open_at'=>'06:30:00', 'close_at'=>'21:00:00',
            'description'=>'Bánh mì Long Hội được ra đời từ niềm đam mê và được biết đến nhờ vào chất lượng và vị thơm ngon của bánh. Giá trị cốt lõi của Bánh mì Long Hội là “Uy tín – An toàn – Chất lượng”. Bánh mì Long Hội sẽ luôn nỗ lực không ngừng để đảm bảo cùng lúc 3 giá trị cốt lõi đó.',
            'image'=>'https://media-cdn.tripadvisor.com/media/photo-p/23/bf/2d/13/banh-m-long-h-i-s-1-hang.jpg',
            'star'=>5.0,
            'min_price'=>30000, 'max_price'=>50000,
            'is_hot'=>1, 'is_active'=>1],

            ['district_id'=>4,
            'name'=>'ESSENCE Restaurant',
            'address'=>'38A Trần Phú, Quận Ba Đình, Hà Nội, Việt Nam 38A Trần Phú, Quận Ba Đình, Thành Phố Hà Nội, Việt Nam, Hà Nội 100000 Việt Nam',
            'phone'=>'02439352485',
            'website'=>'http://essencedining.com/',
            'open_at'=>'06:30:00', 'close_at'=>'22:00:00',
            'description'=>'Nhà hàng Essence Restaurant tọa lạc trên tầng 9-10 của khách sạn Aira Boutique Hanoi Hotel & Spa, vị trí đắc địa số 38A Trần Phú, Quận Ba Đình. Essence Restaurant phục vụ thực đơn cực chất lượng và độc đáo, đa dạng không những các món ăn Việt Nam chính thống mà còn cả những món ăn Châu Âu trong không gian được thiết kế vô cùng thanh lịch, tinh tế không góc chết. Các món ăn vừa ngon miệng vừa đẹp mắt bởi cách bày trí vô cùng chất. Các nguyên liệu chế biến cũng được chọn lọc kỹ càng đảm bảo dinh dưỡng, vệ sinh và độ tươi ngon. Mức giá có một không hai kết hợp với phong cách trang trí lạ mắt mang cả nét đẹp Việt Nam xưa và thiết kế hiện đại tiên tiến, Essence Restaurant được nhiều thực khách đánh giá là nhà hàng tốt nhất thủ đô.',
            'image'=>'https://media-cdn.tripadvisor.com/media/photo-s/22/ac/cb/21/luxury-decoration-essence.jpg',
            'star'=>5.0,
            'min_price'=>116279, 'max_price'=>465116,
            'is_hot'=>0, 'is_active'=>1],

            ['district_id'=>2,
            'name'=>'Tung\'s Kitchen',
            'address'=>'2 Hang Bong, Hà Nội 100000 Việt Nam',
            'phone'=>'02439352575',
            'website'=>'http://www.facebook.com/Tungskitchen/',
            'open_at'=>'10:00:00', 'close_at'=>'22:00:00',
            'description'=>'Chúng tối là gia đình Việt Nam hiện đang sinh sống và làm việc tại Hà Nội. Mong muốn của chúng tôi muốn mang ẩm thực Việt Nam giới thiệu cho tất cả bạn bè trong nước cũng như ngoài nước.',
            'image'=>'https://media-cdn.tripadvisor.com/media/photo-s/26/38/e6/d9/we-are-re-opening-from.jpg',
            'star'=>5.0,
            'min_price'=>46512, 'max_price'=>209302,
            'is_hot'=>1, 'is_active'=>1],

            ['district_id'=>2,
            'name'=>'The Rhythms Restaurant',
            'address'=>'33 - 35 Hàng Dầu Hoàn Kiếm, Hà Nội 100000 Việt Nam',
            'phone'=>'02432121155',
            'website'=>'http://www.therhythmsrestaurant.com/',
            'open_at'=>'11:00:00', 'close_at'=>'22:00:00',
            'description'=>'',
            'image'=>'https://media-cdn.tripadvisor.com/media/photo-s/1a/24/e6/a3/we-create-menu-that-highlights.jpg',
            'star'=>5.0,
            'min_price'=>139535, 'max_price'=>3488372,
            'is_hot'=>0, 'is_active'=>1],

            ['district_id'=>1,
            'name'=>'Hill Top Curry Indian Restaurant',
            'address'=>'118 Yen Phu, Tay Ho, Hà Nội 10000 Việt Nam',
            'phone'=>'0335509430',
            'website'=>'http://hilltopcurry.com/',
            'open_at'=>'10:30:00', 'close_at'=>'22:30:00',
            'description'=>'',
            'image'=>'https://media-cdn.tripadvisor.com/media/photo-s/28/58/c2/00/interior-look-of-hill.jpg',
            'star'=>3.0,
            'min_price'=>99000, 'max_price'=>115000,
            'is_hot'=>0, 'is_active'=>1],

            ['district_id'=>5,
            'name'=>'The Hung Ha Noi Snake Restaurant',
            'address'=>'37 Ng. 137 Việt Hưng Long Biên, Hà Nội 100000 Việt Nam',
            'phone'=>'0989331012',
            'website'=>'https://www.instagram.com/lematsnakevillage/',
            'open_at'=>'09:00:00', 'close_at'=>'23:00:00',
            'description'=>'',
            'image'=>'https://media-cdn.tripadvisor.com/media/photo-s/25/14/61/84/the-hung-ha-noi-snake.jpg',
            'star'=>5.0,
            'min_price'=>255814, 'max_price'=>3488372,
            'is_hot'=>1, 'is_active'=>1],

            ['district_id'=>2,
            'name'=>'Skyline Hanoi',
            'address'=>'38 Gia Ngữ, Hoàn Kiếm Tầng 13, Hà Nội Việt Nam',
            'phone'=>'0968083066',
            'website'=>'http://www.skylinehanoi.com/',
            'open_at'=>'09:00:00', 'close_at'=>'23:00:00',
            'description'=>'SKYLINE còn hơn là nhà hàng hay quầy rượu. Chúng tôi là "Mái nhà của Phố Cổ", đem đến cho khách hàng những trải nghiệm dịch vụ cá nhân với sự tập trung đến từng chi tiết trong mọi thứ chúng tôi phục vụ. Người Việt Nam thường nói, nếu chưa đến Phố Cổ thì chưa hiểu Hà Nội. Nhưng nếu bạn muốn có một cái nhìn tốt nhất về Hà Nội, bạn nên đến với chúng tôi - Mái nhà của Phố Cổ.',
            'image'=>'https://media-cdn.tripadvisor.com/media/photo-s/23/a2/b9/72/oasis-in-the-old-quarter.jpg',
            'star'=>5.0,
            'min_price'=>232558, 'max_price'=>930233,
            'is_hot'=>0, 'is_active'=>1],
        ]);
    }
}
